blank_issues_enabled: false
contact_links:
  - name: 🛒 Chrome Web Store
    url: https://chromewebstore.google.com/detail/funpay-tools/pibmnjjfpojnakckilflcboodkndkibb/
    about: Установить расширение и оставить отзыв
