// ── Robust JSON extractor ─────────────────────────────────────────────────────
// Handles: ```json ... ```, extra text before/after, single quotes, trailing commas
function robustExtractJSON(text) {
    if (!text) return null;

    // 1. Strip markdown code fences: ```json ... ``` or ``` ... ```
    text = text.replace(/^```(?:json)?\s*/im, '').replace(/\s*```\s*$/im, '').trim();

    // 2. Strip leading/trailing non-JSON text
    // Find first [ or { and last ] or }
    const firstBracket = Math.min(
        text.indexOf('[') === -1 ? Infinity : text.indexOf('['),
        text.indexOf('{') === -1 ? Infinity : text.indexOf('{')
    );
    const lastArray  = text.lastIndexOf(']');
    const lastObject = text.lastIndexOf('}');

    if (firstBracket === Infinity) return null;

    const isArray  = text[firstBracket] === '[';
    const lastChar = isArray ? lastArray : lastObject;
    if (lastChar === -1 || lastChar < firstBracket) return null;

    let candidate = text.slice(firstBracket, lastChar + 1);

    // 3. Fix common AI JSON mistakes:
    // - Trailing commas before ] or }
    candidate = candidate.replace(/,(\s*[}\]])/g, '$1');
    // - Single quotes → double quotes (simple cases)
    candidate = candidate.replace(/'([^']+)'(\s*:)/g, '"$1"$2');
    candidate = candidate.replace(/:\s*'([^']*)'/g, ': "$1"');

    return candidate;
}

function robustParseArray(text) {
    const candidate = robustExtractJSON(text);
    if (!candidate || candidate[0] !== '[') return null;
    try {
        const parsed = JSON.parse(candidate);
        return Array.isArray(parsed) && parsed.length > 0 ? parsed : null;
    } catch (_) { return null; }
}

function robustParseObject(text) {
    const candidate = robustExtractJSON(text);
    if (!candidate || candidate[0] !== '{') return null;
    try {
        const parsed = JSON.parse(candidate);
        return typeof parsed === 'object' && parsed !== null ? parsed : null;
    } catch (_) { return null; }
}

// content/features/ai_lot_audit.js - FunPay Funcy 2.9 (full rewrite)
// Survey-style audit: AI generates ~40 questions, user answers, AI gives recommendations.
// Question types: yesno, choice, rating, text, number

let _auditData = null;   // { lots, reviews, username }
let _questions  = [];    // generated by AI, parsed from JSON
let _answers    = {};    // { qIndex: answer }
let _currentQ   = 0;

// ── Phase 1: Load user data ─────────────────────────────────────────────────
async function auditLoadData() {
    const raw = document.body?.dataset?.appData;
    if (!raw) throw new Error('Нет данных авторизации');
    const d = JSON.parse(raw);
    const u = Array.isArray(d) ? d[0] : d;
    const userId   = u?.userId;
    const username = u?.userName || 'Продавец';
    if (!userId) throw new Error('Нет userId');

    // Get lots via existing message handler
    const lots = await new Promise((resolve, reject) => {
        chrome.runtime.sendMessage({ action: 'getUserLotsList', userId }, (res) => {
            if (chrome.runtime.lastError) reject(new Error(chrome.runtime.lastError.message));
            else resolve(res || []);
        });
    });

    // Get reviews via fetch
    let reviews = [];
    try {
        const res = await fetch(`https://funpay.com/users/${userId}/?reviewsPage=1`, { credentials: 'include' });
        if (res.ok) {
            const html = await res.text();
            const doc  = new DOMParser().parseFromString(html, 'text/html');
            Array.from(doc.querySelectorAll('.review-item')).slice(0, 30).forEach(el => {
                const text   = el.querySelector('.review-item-text')?.textContent.trim() || '';
                const rClass = Array.from(el.querySelector('[class*="rating"]')?.classList || []).find(c => /^rating\d/.test(c));
                const stars  = rClass ? parseInt(rClass.replace('rating',''), 10) : 0;
                const lotT   = el.querySelector('.review-lot-title, .review-item-lot')?.textContent.trim() || '';
                if (text) reviews.push({ stars, text: text.slice(0, 120), lot: lotT });
            });
        }
    } catch (_) {}

    return { lots, reviews, username };
}

// ── Phase 2: Generate questions (AI call 1) ─────────────────────────────────
async function auditGenerateQuestions(data) {
    const realLots    = data.lots.slice(0, 60);
    const lotsText    = realLots.map((l, i) => `${i+1}. [${l.categoryName || '-'}] "${l.title}"`).join('\n');
    const totalLots   = realLots.length; // cap at 60 - don't confuse AI with huge numbers

    const vagueTitle  = realLots.filter(l => l.title.length < 10 || /^лот|^товар|^услуга|тест|demo|копир/i.test(l.title));
    const longTitle   = realLots.filter(l => l.title.length > 80);
    const gameList    = [...new Set(realLots.map(l => l.categoryName).filter(Boolean))].slice(0, 10);
    const probeLots   = realLots
        .filter(l => /неполн|базов|без|старый|новый|тест|old|new|v\d|часть|part/i.test(l.title))
        .slice(0, 4)
        .map(l => `"${l.title}"`);

    // Build conditional sections - only mention real problems that actually exist
    const titleIssues = [
        vagueTitle.length ? `  • Лоты с очень коротким или расплывчатым названием: ${vagueTitle.map(l => '"'+l.title+'"').join(', ')} - спроси конкретно что продаётся в каждом из них` : '',
        longTitle.length  ? `  • Лоты с названием длиннее 80 символов: ${longTitle.map(l => '"'+l.title+'"').slice(0,3).join(', ')} - спроси, первые 40 символов содержат суть или воду?` : '',
        probeLots.length  ? `  • Лоты с подозрительными словами (тест/старый/неполный): ${probeLots.join(', ')} - спроси про каждый конкретно` : '',
    ].filter(Boolean).join('\n') || '  • Спроси есть ли в названиях что-то уникальное (УТП) или они выглядят как у всех конкурентов';

    const prompt = `Ты - аналитик рекламных объявлений на FunPay.com.
FunPay - маркетплейс игровых товаров. Покупатели ищут через поиск, сортируют по цене. Дешевле = выше.

ЛОТЫ ПРОДАВЦА (показаны ${totalLots} из ${data.lots.length}):
${lotsText}

КАТЕГОРИИ: ${gameList.join(', ')}

ПРАВИЛА FunPay которые влияют на продажи:
- Название обрезается после ~50 символов в списке - начало названия критично
- Лоты без фото получают меньше кликов
- Продавец может дублировать лоты по серверам - это нормально, не спрашивай об этом

ЗАДАЧА: Сгенерируй РОВНО 30 вопросов строго по РЕАЛЬНЫМ лотам выше.

ЖЁСТКИЕ ЗАПРЕТЫ:
✗ НЕ придумывай лоты которых нет в списке выше
✗ НЕ спрашивай про отзывы, клиентский сервис, скорость ответа
✗ НЕ спрашивай "как давно продаёте", "что для вас важно", абстрактные вопросы
✗ НЕ спрашивай про автовыдачу, авто-поднятие, дублирование по серверам
✗ НЕ задавай вопросы рейтинга 1-5

ТЕМЫ (все вопросы - про конкретные лоты из списка):

- НАЗВАНИЯ (7-9 вопросов):
${titleIssues}
  • Есть ли лот название которого не отличается от конкурентов - что уникального можно добавить?

- ЦЕНЫ (8-10 вопросов):
  • Для каждой категории из списка: текущая цена ниже/равна/выше минимума в категории?
  • Тестировал снижение цены на 10-15% - как влияло на заказы?
  • Есть ли лоты с ценой которую не менял больше месяца?
  • Если несколько лотов в одной категории - чем обоснована разница в цене?

- ОПИСАНИЕ И ФОТО (6-8 вопросов):
  • На каких конкретных лотах нет фото?
  • В описании написано конкретно что получит покупатель, или общие слова ("быстро", "качественно")?
  • Указано время выдачи и онлайн-часы - или покупатель не знает когда ждать?

- ПРОДАЖИ (4-6 вопросов):
  • Какой лот из списка приносит больше всего денег и почему?
  • Есть ли лот который хочешь продавать больше, но он плохо идёт?
  • Какой лот чаще всего видят но не покупают?

Формат - ТОЛЬКО JSON массив, без markdown, без текста до или после:
[
  {"id":1,"q":"Вопрос про конкретный лот?","type":"yesno"},
  {"id":2,"q":"Вопрос с вариантами?","type":"choice","opts":["А","Б","В"]},
  {"id":3,"q":"Открытый вопрос?","type":"text"}
]`;

    const res = await new Promise((resolve) => {
        chrome.runtime.sendMessage({
            action: 'getAIProcessedText',
            text: prompt,
            context: '',
            myUsername: data.username,
            type: 'lot_audit_raw'
        }, resolve);
    });

    if (!res?.success) throw new Error(res?.error || 'Ошибка ИИ при генерации вопросов');

    const questions = robustParseArray(res.data);
    if (!questions) throw new Error('ИИ вернул некорректный формат. Попробуйте ещё раз.');
    return questions;
}

// ── Phase 3: Generate recommendations (AI call 2) ───────────────────────────
async function auditGenerateRecommendations(data, questions, answers) {
    const qaText = questions.map((q, i) => {
        const ans = answers[i] ?? '(не ответил)';
        return `Q${i+1}: ${q.q}\nA: ${ans}`;
    }).join('\n\n');

    const lotsText = data.lots.slice(0, 50).map(l => `"${l.title}" [${l.categoryName}]`).join(', ');

    const prompt = `Ты - аналитик рекламных объявлений FunPay. Тебе предоставлены лоты продавца и его ответы на вопросы аудита.

ЛОТЫ: ${lotsText}

ОТВЕТЫ ПРОДАВЦА НА ВОПРОСЫ АУДИТА:
${qaText}

КАК РАБОТАЕТ РАНЖИРОВАНИЕ НА FUNPAY:
- В поиске выше тот, у кого ниже цена И свежее поднятие (раз в 4 часа максимум)
- Покупатель ищет точными словами: "1000 голды", "купить ключ", "сервер Гордунни"
- Лот без фото = меньше кликов в среднем
- Первые 40 символов названия - единственное что видно в поисковой выдаче до обрезки

ПРАВИЛА РЕКОМЕНДАЦИЙ:
✗ ЗАПРЕЩЕНО: советы про общение, сервис, клиентов, отзывы, вежливость, скорость ответа
✗ ЗАПРЕЩЕНО: общие фразы без конкретного лота ("улучшите описания", "следите за ценами")
✓ КАЖДАЯ рекомендация должна называть конкретный лот по имени или конкретную цифру

ПРИМЕРЫ ХОРОШИХ рекомендаций:
✓ "Лот \"Голда WoW\" - переименуйте в \"1000 Голды WoW Classic Пламегор\" (сервер + количество = ключевые слова)"
✓ "Лот \"Ключ Steam\" стоит 299₽ - если в категории минимум 250₽, снизьте до 255₽ чтобы попасть в топ"
✓ "Лот \"Аккаунт Minecraft\" - добавьте скриншот инвентаря или уровня, без фото CTR ниже"
✓ "Поднятие раз в день - этого мало, лот уходит в конец за 4 часа. Нужно поднятие каждые 4 часа"
✓ "В описании лота \"X\" не указано время выдачи - покупатели уходят к конкурентам у кого написано \"онлайн 24/7\""

Формат ответа - ТОЛЬКО JSON, без markdown:
{
  "critical": ["Самое важное что нужно сделать прямо сейчас - с конкретным лотом", "..."],
  "titles": ["Лот \"X\" - конкретное новое название вместо старого", "..."],
  "pricing": ["Лот \"X\" - конкретное ценовое действие", "..."],
  "visibility": ["Конкретное действие по поднятию/фото/описанию с названием лота", "..."],
  "summary": "1-2 предложения: главная слабая точка продавца и один главный приоритет"
}`;

    const res = await new Promise((resolve) => {
        chrome.runtime.sendMessage({
            action: 'getAIProcessedText',
            text: prompt,
            context: '',
            myUsername: data.username,
            type: 'lot_audit_raw'
        }, resolve);
    });

    if (!res?.success) throw new Error(res?.error || 'Ошибка ИИ при генерации рекомендаций');

    const recs = robustParseObject(res.data);
    if (recs) return recs;
    // Fallback: wrap raw text as summary
    return { summary: res.data.slice(0, 500), critical: [], titles: [], pricing: [], visibility: [], automation: [] };
}

// ── UI helpers ───────────────────────────────────────────────────────────────
function auditSetState(state) {
    // state: 'start' | 'loading' | 'survey' | 'processing' | 'results'
    const startWrap  = document.getElementById('fp-audit-start-wrap');
    const loadingEl  = document.getElementById('fp-audit-loading');
    const surveyEl   = document.getElementById('fp-audit-survey');
    const procEl     = document.getElementById('fp-audit-processing');
    const resultsEl  = document.getElementById('fp-audit-results');

    [startWrap, loadingEl, surveyEl, procEl, resultsEl].forEach(el => {
        if (el) el.style.display = 'none';
    });

    const map = { start: startWrap, loading: loadingEl, survey: surveyEl, processing: procEl, results: resultsEl };
    if (map[state]) map[state].style.display = 'block';
}

function auditRenderQuestion(index) {
    const q = _questions[index];
    if (!q) return;

    _currentQ = index;

    const container = document.getElementById('fp-audit-q-container');
    if (!container) return;

    const progress = Math.round(((index) / _questions.length) * 100);

    document.getElementById('fp-audit-progress-bar').style.width = progress + '%';
    document.getElementById('fp-audit-q-num').textContent = `Вопрос ${index + 1} из ${_questions.length}`;

    container.innerHTML = '';

    const qText = document.createElement('div');
    qText.style.cssText = 'font-size:14px;color:#eceef6;margin-bottom:16px;line-height:1.5;font-weight:500;';
    qText.textContent = q.q;
    container.appendChild(qText);

    let getValue = () => '';

    if (q.type === 'yesno') {
        const wrap = document.createElement('div');
        wrap.style.cssText = 'display:flex;gap:10px;';
        ['Да', 'Нет'].forEach(opt => {
            const btn = document.createElement('button');
            btn.textContent = opt;
            btn.dataset.val = opt;
            btn.className = 'fp-audit-opt';
            btn.style.cssText = `flex:1;padding:12px;border:2px solid var(--fpt-border, rgba(0,0,0,0.12));border-radius:8px;background:var(--fpt-bg, #ffffff);color:var(--fpt-text, #16181d);cursor:pointer;font-size:14px;font-family:inherit;transition:all .15s;`;
            btn.addEventListener('click', () => {
                wrap.querySelectorAll('.fp-audit-opt').forEach(b => {
                    b.style.borderColor = '#22253a'; b.style.background = '#1a1c2e'; b.style.color = '#d8dae8';
                });
                btn.style.borderColor = '#1b75bb'; btn.style.background = 'rgba(27,117,187,0.16)'; btn.style.color = '#4a9fd4';
                btn.dataset.selected = '1';
            });
            wrap.appendChild(btn);
        });
        getValue = () => {
            const sel = wrap.querySelector('[data-selected="1"]');
            return sel ? sel.dataset.val : '';
        };
        container.appendChild(wrap);

    } else if (q.type === 'choice') {
        const opts = q.opts || [];
        const wrap = document.createElement('div');
        wrap.style.cssText = 'display:flex;flex-direction:column;gap:8px;';
        opts.forEach(opt => {
            const btn = document.createElement('button');
            btn.textContent = opt;
            btn.dataset.val = opt;
            btn.className = 'fp-audit-opt';
            btn.style.cssText = `padding:10px 14px;border:2px solid var(--fpt-border, rgba(0,0,0,0.12));border-radius:8px;background:var(--fpt-bg, #ffffff);color:var(--fpt-text, #16181d);cursor:pointer;font-size:13px;text-align:left;font-family:inherit;transition:all .15s;`;
            btn.addEventListener('click', () => {
                wrap.querySelectorAll('.fp-audit-opt').forEach(b => {
                    b.style.borderColor = '#22253a'; b.style.background = '#1a1c2e'; b.style.color = '#d8dae8';
                });
                btn.style.borderColor = '#1b75bb'; btn.style.background = 'rgba(27,117,187,0.16)'; btn.style.color = '#4a9fd4';
                btn.dataset.selected = '1';
            });
            wrap.appendChild(btn);
        });
        getValue = () => {
            const sel = wrap.querySelector('[data-selected="1"]');
            return sel ? sel.dataset.val : '';
        };
        container.appendChild(wrap);

    } else if (q.type === 'rating') {
        const wrap = document.createElement('div');
        wrap.style.cssText = 'display:flex;gap:8px;align-items:center;';
        const labels = ['', 'Очень плохо', 'Плохо', 'Средне', 'Хорошо', 'Отлично'];
        let selectedRating = 0;
        for (let i = 1; i <= 5; i++) {
            const star = document.createElement('button');
            star.textContent = '★';
            star.dataset.val = String(i);
            star.title = labels[i];
            star.style.cssText = `background:none;border:none;font-size:28px;cursor:pointer;color:#2a2d44;transition:color .1s;padding:0 2px;`;
            star.addEventListener('click', () => {
                selectedRating = i;
                wrap.querySelectorAll('button').forEach((s, idx) => {
                    s.style.color = idx < i ? '#FFD700' : '#2a2d44';
                });
            });
            star.addEventListener('mouseenter', () => {
                const v = parseInt(star.dataset.val);
                wrap.querySelectorAll('button').forEach((s, idx) => {
                    s.style.color = idx < v ? '#FFD700' : '#2a2d44';
                });
            });
            star.addEventListener('mouseleave', () => {
                wrap.querySelectorAll('button').forEach((s, idx) => {
                    s.style.color = idx < selectedRating ? '#FFD700' : '#2a2d44';
                });
            });
            wrap.appendChild(star);
        }
        const labelEl = document.createElement('span');
        labelEl.style.cssText = 'font-size:12px;color:var(--fpt-text-muted, #8a90a6);margin-left:6px;';
        wrap.appendChild(labelEl);
        getValue = () => selectedRating ? `${selectedRating}/5 - ${labels[selectedRating]}` : '';
        container.appendChild(wrap);

    } else {
        // text (default)
        const ta = document.createElement('textarea');
        ta.placeholder = 'Ваш ответ...';
        ta.style.cssText = `width:100%;height:80px;background:var(--fpt-surface, #f5f7fa);border:1px solid var(--fpt-border, rgba(0,0,0,0.12));border-radius:8px;padding:10px;color:var(--fpt-text, #16181d);font-size:13px;resize:vertical;outline:none;font-family:inherit;box-sizing:border-box;`;
        ta.addEventListener('focus', () => ta.style.borderColor = '#1b75bb');
        ta.addEventListener('blur',  () => ta.style.borderColor = '#22253a');
        getValue = () => ta.value.trim();
        container.appendChild(ta);
        setTimeout(() => ta.focus(), 50);
    }

    // Restore previous answer if any
    const prev = _answers[index];
    if (prev !== undefined) {
        if (q.type === 'yesno' || q.type === 'choice') {
            container.querySelectorAll('.fp-audit-opt').forEach(btn => {
                if (btn.dataset.val === prev) {
                    btn.click();
                }
            });
        } else if (q.type === 'rating') {
            const r = parseInt(prev);
            if (r) container.querySelectorAll('button')[r - 1]?.click();
        } else {
            container.querySelector('textarea').value = prev;
        }
    }

    // Store getValue for the Next/Finish button
    container._getValue = getValue;
}

function auditShowResults(recs) {
    auditSetState('results');
    const el = document.getElementById('fp-audit-results');
    if (!el) return;

    const section = (title, items, color) => {
        if (!items?.length) return '';
        return `<div style="margin-bottom:16px;">
            <div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:.5px;color:${color};margin-bottom:8px;">${title}</div>
            ${items.map(it => `<div style="background:var(--fpt-surface, #f5f7fa);border-left:3px solid ${color};border-radius:0 6px 6px 0;padding:8px 12px;margin-bottom:6px;font-size:13px;color:var(--fpt-text, #16181d);line-height:1.4;">${it}</div>`).join('')}
        </div>`;
    };

    el.innerHTML = `
        <div style="background:var(--fpt-bg, #ffffff);border-radius:8px;padding:14px;margin-bottom:16px;font-size:13px;color:#c0c4d8;line-height:1.5;">
            <strong style="color:#eceef6;">Резюме:</strong><br>${recs.summary || ''}
        </div>
        ${section('🔴 Критично - исправить первым делом', recs.critical, '#e05252')}
        ${section('📝 Названия и описания', recs.titles, '#FF6B6B')}
        ${section('💰 Цены', recs.pricing, '#ff9800')}
        ${section('🔍 Видимость в поиске', recs.visibility, '#1b75bb')}
        ${section('💬 Клиентский сервис', recs.service, '#4caf82')}
        <button onclick="document.getElementById('fp-audit-start-btn').click()" style="margin-top:10px;background:var(--fpt-bg, #ffffff);border:1px solid var(--fpt-border, rgba(0,0,0,0.12));border-radius:6px;padding:8px 16px;color:var(--fpt-text-muted, #6b7280);cursor:pointer;font-size:13px;font-family:inherit;">Начать заново</button>
    `;
}

// ── Main init ────────────────────────────────────────────────────────────────
function initializeAILotAudit() {
    const page = document.querySelector('.fp-tools-page-content[data-page="ai_audit"]');
    if (!page || page.dataset.initialized) return;
    page.dataset.initialized = 'true';

    const startBtn = document.getElementById('fp-audit-start-btn');
    const nextBtn  = document.getElementById('fp-audit-next-btn');
    const prevBtn  = document.getElementById('fp-audit-prev-btn');

    if (!startBtn) return;

    const AUDIT_COOLDOWN_KEY = 'fpAuditLastRun';
    const AUDIT_COOLDOWN_MS  = 30 * 24 * 60 * 60 * 1000; // 30 days

    async function auditCheckCooldown() {
        const d = await chrome.storage.local.get(AUDIT_COOLDOWN_KEY);
        const last = d[AUDIT_COOLDOWN_KEY] || 0;
        const elapsed = Date.now() - last;
        return { allowed: elapsed >= AUDIT_COOLDOWN_MS, remainMs: AUDIT_COOLDOWN_MS - elapsed };
    }

    async function auditApplyCooldownUI() {
        const { allowed, remainMs } = await auditCheckCooldown();
        const cooldownMsg = document.getElementById('fp-audit-cooldown-msg');
        if (!allowed) {
            startBtn.disabled = true;
            startBtn.style.opacity = '0.5';
            if (cooldownMsg) {
                const days  = Math.ceil(remainMs / (24 * 60 * 60 * 1000));
                const hours = Math.ceil(remainMs / (60 * 60 * 1000));
                cooldownMsg.style.display = 'block';
                cooldownMsg.textContent = days > 1
                    ? `⏳ Следующий аудит будет доступен через ${days} дн.`
                    : `⏳ Следующий аудит будет доступен через ${hours} ч.`;
            }
        } else {
            startBtn.disabled = false;
            startBtn.style.opacity = '';
            if (cooldownMsg) cooldownMsg.style.display = 'none';
        }
    }

    auditApplyCooldownUI();

    startBtn.addEventListener('click', async () => {
        const { allowed } = await auditCheckCooldown();
        if (!allowed) { showNotification('Аудит доступен раз в месяц.', true); return; }
        await chrome.storage.local.set({ [AUDIT_COOLDOWN_KEY]: Date.now() });
        auditApplyCooldownUI();
        auditSetState('loading');
        _answers = {};
        _questions = [];
        _currentQ = 0;

        try {
            document.getElementById('fp-audit-loading').textContent = '⏳ Загружаем лоты и отзывы...';
            _auditData = await auditLoadData();

            document.getElementById('fp-audit-loading').textContent = `✅ Загружено ${_auditData.lots.length} лотов, ${_auditData.reviews.length} отзывов.\n⏳ ИИ генерирует вопросы...`;
            _questions = await auditGenerateQuestions(_auditData);

            auditSetState('survey');
            auditRenderQuestion(0);

        } catch (e) {
            auditSetState('start');
            showNotification(`Ошибка: ${e.message}`, true);
        }
    });

    if (nextBtn) {
        nextBtn.addEventListener('click', async () => {
            const container = document.getElementById('fp-audit-q-container');
            const val = container?._getValue?.() ?? '';

            // Save answer
            _answers[_currentQ] = val;

            if (_currentQ >= _questions.length - 1) {
                // Finish - generate recommendations
                auditSetState('processing');
                try {
                    const recs = await auditGenerateRecommendations(_auditData, _questions, _answers);
                    auditShowResults(recs);
                } catch (e) {
                    auditSetState('survey');
                    showNotification(`Ошибка: ${e.message}`, true);
                }
            } else {
                auditRenderQuestion(_currentQ + 1);
                // Update button label
                nextBtn.textContent = _currentQ >= _questions.length - 1 ? '✅ Завершить' : 'Далее →';
            }

            // Update next button
            if (_currentQ < _questions.length - 1) {
                nextBtn.textContent = _currentQ + 1 >= _questions.length - 1 ? '✅ Завершить' : 'Далее →';
            }
        });
    }

    if (prevBtn) {
        prevBtn.addEventListener('click', () => {
            if (_currentQ > 0) {
                // Save current before going back
                const container = document.getElementById('fp-audit-q-container');
                const val = container?._getValue?.() ?? '';
                _answers[_currentQ] = val;
                auditRenderQuestion(_currentQ - 1);
                if (nextBtn) nextBtn.textContent = 'Далее →';
            }
        });
    }
}